# source("code/.R")

source("code/format_veg_data/get_site_data_forgroups.R")
source("code/format_veg_data/get_park_data.R")
source("code/format_veg_data/local_diversity.R")
source("code/format_veg_data/FIA_getdata.R")
source("code/format_veg_data/get_coun_data.R")
source("code/format_bird_data/2_create_data_files.R")
source("code/format_bird_data/2_create_data_files.R")
source("code/format_bird_data/check_sps_data.r.R")
# source("code/fit_model/back2d_covs_scales.R")
# source("code/fit_model/multiple_single_sps.R")
