source("code/format_veg_data/get_site_data_forgroups.R")
source("code/format_veg_data/get_park_data.R")
source("code/format_veg_data/local_diversity.R")
source("code/format_veg_data/FIA_getdata.R")
source("code/format_veg_data/get_coun_data.R")
source("code/format_bird_data/2_create_data_files.R")
source("code/format_bird_data/2_create_data_files_yr.R")
source("code/fit_model/multiple_single_sps_spscov.R")
source("code/fit_model/multiple_single_sps_spscov_yr.R")

# source("code/")
# source("code/")
# source("code/")
