#? *********************************************************************************
#? ----------------------------   get_site_data_rad.R   ----------------------------
#? *********************************************************************************
#! Code to get site values for forest covariates. First, it gets the locations and forest types
#!    of each bird site and forest plot, and connect them. Bird sites are characterized with forest
#!    structure variables for all the forest plots that are within the same forest type as all the
#!    forest plots.
#
#! Source ---------------------------------------------
#           - :
#           - :
#
#! Input ----------------------------------------------
#           - data/out/for_plot_covs.rds    : forest oplot covariates for each forest plot generated by NETN_forest_data_for_pltes.R
#           - data/out/updated_for_cats.csv : vegetation types/categories of the parks - detailed to be classified in forest/not forest
#           - data/VAMA_sites.rds           : file to get forest plot names for VAMA that are not named after ROVA
#           - data/HOFR_sites.rds           : file to get forest plot names for HOFR that are not named after ROVA
#           - data/ELRO_sites.rds           : file to get forest plot names for ELRO that are not named after ROVA
#           - data/src/key_park.rds         : file with all park names
#           - data/out/key_bsite.rds        : forest type classification fore ach bird site
#           - data/out/key_fsite.rds        : forest type classification fore ach forest plot
#
#! Output ----------------------------------------------
#           - data/out/site_covs_fornofor_{radi_dist}m.rds : forest covariates for each bird site according to the weighted mean by distance of the closest 5 forest plots
#           - data/out/neighbor_fornofor_{radi_dist}m.rds  : who is whose neighbor
#           - data/out/site_covs_hardcon_{radi_dist}m.rds : forest covariates for each bird site according forest type and to the weighted mean by distance of the closest 5 forest plots
#           - data/out/neighbor_hardcon_{radi_dist}m.rds  : who is whose neighbor with forest type
#
# detach packages and clear workspace
freshr::freshr()
#
#! Load packages ---------------------------------------
#library(conflicted)
library(tidyverse)
library(glue)
library(sp)
#library(rgdal)
library(sf)
library(reshape2)
library(ggplot2)
library(ggh4x)
#library("MetBrewer")
library(forestNETN)

#conflicts_prefer(dplyr::select)
#conflicts_prefer(dplyr::filter)
# conflicts_prefer(scales::alpha)
#
#! Make functions --------------------------------------
colanmes <- colnmaes <- colnames
lenght <- length
`%!in%` <- Negate(`%in%`)

Modes <- function(x) {
  ux <- unique(x)
  tab <- tabulate(match(x, ux))
  if(length(ux[tab == max(tab)]) > 1) {
    sample(ux[tab == max(tab)], 1)
    } else {
      ux[tab == max(tab)]}
}
#! Define settings -------------------------------------
# radius distance in meters
radi_dist2 <- 400
hard_con_mix2 <- FALSE 

if(exists("radi_dist") == FALSE) {radi_dist <- radi_dist2}
if(exists("hard_con_mix") == FALSE) {hard_con_mix <- hard_con_mix2}

print(glue("\n\n\n\n\n\n radius distance is {radi_dist} \n\n\n\n\n\n"))
print(glue("\n\n\n\n\n\n are we using conifer and hardwood to decide neighbors? {hard_con_mix} \n\n\n\n\n\n"))

#! Import data -----------------------------------------
## file paths
BIRD_SITE_PATH <- "data/out/NETNtib.rds"
BIRD_FOR_PATH  <- "data/out/key_bsite.rds"
FOR_FOR_PATH   <- "data/out/key_fsite.rds"

PARK_SITE_PATH <- "data/key_park.rds"
FOR_PLOT_COVS  <- "data/out/for_plot_covs.rds"
VEG_TYP_PATH   <- "data/out/updated_for_cats.csv"   
UTM_BIRD_SIT   <- "data/out/park_site_UTM.rds"

## read files
bird_sit       <- read_rds(file = BIRD_SITE_PATH)
parks          <- read_rds(file = PARK_SITE_PATH) 
veg_type       <- read_csv(file = VEG_TYP_PATH)
for_plt        <- read_rds(file = FOR_PLOT_COVS)

bird_cat       <- read_rds(file = BIRD_FOR_PATH)
for_cat        <- read_rds(file = FOR_FOR_PATH)
bird_coord_utm <- read_rds(file = UTM_BIRD_SIT)

#! get coordinates from the bird sites ------------------------------
parks <- parks %>% 
  dplyr::select(parks) %>% 
  distinct() %>% 
  filter(parks %!in% c("ACAD", "ELRO", "SAIR")) %>%
  pull()

parks <- sort(parks) 

# get UTM coordinates for all points
for(ii in 1:length(bird_sit$points)){
  coord_loop <- 
    bird_sit$points[ii][[1]] %>% 
      select(Point_Name, Longitude, Latitude, Survey_Type) %>% 
      mutate(Point_Name2 = glue("{substr(Point_Name, 1, 4)}{substr(Point_Name, 6, 7)}{substr(Point_Name, 10, 11)}")) %>% 
      left_join(., 
                bird_coord_utm %>% 
                    rename(Point_Name2 = Point_Name, Longitude2 =  Longitude, Latitude2 = Latitude), 
                by = "Point_Name2") %>% 
      select(-Latitude2, -Longitude2)  %>% 
      filter(Survey_Type == "Forest")

#! TODO: check with aaron the difference in lat for MIMA1403
  # if(unique(coord_loop$Latitude2 == coord_loop$Latitude) == TRUE & unique(coord_loop$Longitude2 == coord_loop$Longitude) == TRUE) {
  #   print(ii)
  # } else {stop("problem at ii")}

  # coord_loop %>% filter(Point_Name == "MIMA1403") %>% pull(Longitude)

  if(ii == 1) {
    park_site <- coord_loop
  } else {
    park_site <- rbind(park_site, coord_loop)
  }
}

nrow(park_site)

#? write_rds "data/out/park_site.rds"
# write_rds(park_site, file = "data/out/park_site.rds")

# get coordinates from bird plots
bird_sit_coord <- park_site %>% 
  select(Point_Name,
          Latitude,
          Longitude, 
          UTM_ZONE) %>% 
  rename(bird_sit = Point_Name,
          lat = Latitude,
          lon = Longitude,
          UTMZone = UTM_ZONE) 

#! get coordinates from the forest plots ------------------------------
for_plt_coord <- for_plt %>% 
  rename(for_plt = Plot_Name,
          latutm = Y,
          lonutm = X) %>% 
  select(for_plt, latutm, lonutm, UTMZone) %>% 
  mutate(UTMZone = substr(UTMZone, 1 , 2))

colnmaes(for_plt_coord); colnmaes(bird_sit_coord)
#? write_rds for_plt_coord
# write_rds(for_plt_coord, file = "data/out/for_plt_coord.rds")

# par(mfrow = c(1,2))
# plot(for_plt_coord$lonutm, for_plt_coord$latutm, col = "darkgreen")
# plot(bird_sit_coord$lon, bird_sit_coord$lat, col = "violet")

#? convert all bird coordinates to UTM to get distances in meters --------------------
xy <- data.frame(ID = 1:nrow(bird_sit_coord), 
                  X = bird_sit_coord$lon, 
                  Y = bird_sit_coord$lat)
coordinates(xy) <- c("X", "Y")
proj4string(xy) <- CRS("+proj=longlat +datum=WGS84")

# write_rds(xy, file = "data/out/bird_catse_coords.rds")

for(ii in 1:nrow(xy)){
  band <- as.numeric(bird_sit_coord$UTMZone[ii])
  y <- spTransform(xy[ii,], CRS(glue("+proj=utm +zone={band} +datum=WGS84 +units=m")))
  y2 <- as(y, "SpatialPoints") %>% 
        as_tibble()
  y2$UTMZone <- band
  
  if(ii == 1) {
    utm_bir <- y2
  } else {
    utm_bir <- rbind(utm_bir, y2)
  }
  rm(y)
}

colnames(utm_bir) <- c("lonutm", "latutm", "UTMZone")
table(bird_sit_coord$UTMZone == utm_bir$UTMZone)

bird_sit_coord <- cbind(bird_sit_coord, utm_bir[,1:2])

park_plot_nam <- bird_sit_coord %>% 
              mutate(park = substr(bird_sit, 1 , 4)) %>% 
              group_by(park) %>% 
              filter(row_number()==1) %>%
              ungroup()

ggplot() +
  geom_point(aes(x = bird_sit_coord$lonutm, 
                 y = bird_sit_coord$latutm),
             size = 2,
             color = "red") +
  geom_point(aes(x = for_plt_coord$lonutm, 
                 y = for_plt_coord$latutm), 
             color = "darkgreen") +
  #geom_text(aes(x= park_plot_nam$lonutm, y =park_plot_nam$latutm),
  #          label = park_plot_nam$park, size = 3, vjust = -1.3) +
  theme_bw() +
  coord_cartesian(xlim = c(697200, 700200), 
                  ylim = c(4833300, 4835000))

# great - it all alligns very well; now let's get the closest 3 sites

#? Connect forest sites and bird sites -----------------------------------
bird_sit_coord15 <- bird_sit_coord %>% 
    as_tibble() %>% 
    mutate(park = substr(bird_sit, 1 , 4)) %>%
    filter(park != "ACAD",
           park != "ELRO",
           park != "SAIR")

# link forest types with sites
## first clkassify all forest types, so we can classify them in forest and not forest
bird_sit_coord2 <- left_join(bird_sit_coord15 %>% select(-park), 
                              bird_cat %>% 
                                mutate(bird_sit = glue("{substr(Point_Name, 1, 4)}_{substr(Point_Name, 5, 6)}_0{substr(Point_Name, 7, 8)}")) %>% 
                                rename(b_for = MapUnit_ID) %>% 
                                select(bird_sit, b_for),
                              by = "bird_sit") %>% 
                    filter(!is.na(b_for))

# change Rova names to actual parks
ROVA_sites <- for_plt_coord %>% 
                  mutate(park = substr(for_plt, 1, 4)) %>% 
                  filter(park == "ROVA")

plot(ROVA_sites$lonutm, ROVA_sites$latutm)

VAMA_sites <- ROVA_sites %>% 
                  filter(latutm > 4626000,
                         lonutm < 589000) %>% 
                  mutate(park = "VAMA")

points(VAMA_sites$lonutm, VAMA_sites$latutm,  col = "lightgreen")
points(bird_sit_coord15$lonutm, bird_sit_coord15$latutm, col = "purple")

HOFR_sites <- ROVA_sites %>% 
                  filter(latutm < 4626000,
                         lonutm < 589000) %>% 
                  mutate(park = "HOFR")

points(HOFR_sites$lonutm, HOFR_sites$latutm,  col = "black", pch = "*")
points(bird_sit_coord15$lonutm, bird_sit_coord15$latutm, col = "violet")

ELRO_sites <- ROVA_sites %>% 
                  filter(latutm < 4626000,
                         lonutm > 591000) %>% 
                  mutate(park = "ELRO")

points(ELRO_sites$lonutm, ELRO_sites$latutm, col = "blue", pch = 23)

for_plt_coord15 <- for_plt_coord %>% 
                  mutate(park = substr(for_plt, 1, 4)) %>% 
                  filter(park != "ROVA") %>% 
                  rbind(., VAMA_sites, HOFR_sites)

nrow(for_plt_coord15) == nrow(for_plt_coord)  ## the missing sites are all the forest plots that have no bird plots between 'parks'

points(for_plt_coord15$lonutm, for_plt_coord15$latutm, col = "red", pch = "*")

for_plt_coord2 <- left_join(for_plt_coord15, 
                            for_cat %>% 
                              rename(for_plt = ID,
                                     f_for = MapUnit_ID) %>% 
                              select(for_plt, f_for, geometry),
                            by = "for_plt") %>% 
                    filter(!is.na(f_for)) %>% 
                    filter(park != "ROVA")%>% 
                    filter(park != "ELRO")

# get a table with all the forest types to compare to the key, 
#    and possible combine them into two groups: forest not forest
if(hard_con_mix == FALSE) {
  for (ii in 1:nrow(veg_type)){
    if(!is.na(veg_type$Cover_Type[ii]) && veg_type$Cover_Type[ii] != "Not forest") {
        veg_type$Cover_Type[ii] <- "Forest"
        } 
    }
}

veg_type_indata <- c(unique(for_plt_coord2$f_for),
                      unique(bird_sit_coord2$b_for)) %>% 
                      unique() %>% 
                      sort() %>% 
                      as_tibble() %>% 
                      rename(MapUnit_ID = value) %>% 
                      left_join(veg_type, by = "MapUnit_ID")
dim(veg_type_indata)
length(unique(veg_type_indata$MapUnit_ID))
#writexl::write_xlsx(tab_veg3, path = "data/out/tab_veg3.xlsx")

  bird_sit_coord2 <- bird_sit_coord2 %>% 
        rename(MapUnit_ID = b_for) %>% 
        left_join(., veg_type, by = "MapUnit_ID")  %>% 
        rename(bir_veg = Cover_Type)

  for_plt_coord3 <- for_plt_coord2 %>% 
        rename(MapUnit_ID = f_for) %>% 
        left_join(., veg_type, by = "MapUnit_ID") %>% 
        rename(for_veg = Cover_Type) 

if(hard_con_mix == FALSE) {

  # merge forest categories and remove non forest
  bird_sit_coord2 <- bird_sit_coord2 %>% 
        filter(bir_veg == "Forest")

  for_plt_coord3 <- for_plt_coord3 %>% 
        filter(for_veg == "Forest")
}

rbind(
  bird_sit_coord2 %>% filter(!is.na(bir_veg)) %>% select(MapUnit_ID) %>% distinct(),
  for_plt_coord3 %>% filter(!is.na(for_veg)) %>% select(MapUnit_ID) %>% distinct()) %>% 
  distinct() %>% 
  arrange(MapUnit_ID)

# test sites
for_test <- for_plt_coord3 %>% 
              select(park, lonutm, latutm, for_veg)
bir_test <- bird_sit_coord2 %>% 
              mutate(park = substr(bird_sit,1,4)) %>% 
              select(park, lonutm, latutm, bir_veg, bird_sit)
parks_sub <- sort(unique(for_test$park))

par(mfrow = c(1,1))
for(ii in 1:length(parks_sub)){
  for_test2 <- for_test %>% filter(park == parks_sub[ii])
  bir_test2 <- bir_test %>% filter(park == parks_sub[ii])

  plot(for_test2$lonutm, for_test2$latutm, col = "darkgreen", 
      main = for_test2$park[1], pch = 19, cex = 3)
  points(bir_test2$lonutm, bir_test2$latutm, col = "violet", pch = 15, cex = 3)
 # Add text labels for bird sites
  text(x = bir_test2$lonutm, 
       y = bir_test2$latutm, 
       labels = substr(bir_test2$bird_sit, 6, nchar(bir_test2$bird_sit)), 
       #pos = 3, # position above points
       cex = 0.8, 
       col = "black")
}
# get ALL neighbors within the same park, and only keep the ones that have the forest type

for (ii in 1:nrow(bird_sit_coord2)) {

  band <- as.numeric(bird_sit_coord2$UTMZone[ii])
  y <- spTransform(xy[ii,], CRS(glue("+proj=utm +zone={band} +datum=WGS84 +units=m")))

  bird <- st_as_sf(bird_sit_coord2[ii,5:6], 
                    coords=c("lonutm", "latutm"), 
                    crs = CRS(proj4string(y)))

  plop <- substr(bird_sit_coord2$bird_sit[ii], 1, 4)

  for_plt_coord4 <- for_plt_coord3 %>% 
                      filter(park == plop)
  
  print(bird_sit_coord2$bird_sit[ii])

  for(jj in 1:nrow(for_plt_coord4)) {
    # are the bird sites and forest plots in the same forest type?
    # if the answer is yes, we calculate the distance between them
    if((bird_sit_coord2$bir_veg[ii] == for_plt_coord4$for_veg[jj]) == TRUE){
      #print(for_plt_coord4$for_plt[jj])
      #print(jj)

      band2 <- as.numeric(for_plt_coord4$UTMZone[jj])
      x <- spTransform(xy[ii,], CRS(glue("+proj=utm +zone={band2} +datum=WGS84 +units=m")))

      fore <- st_as_sf(for_plt_coord4[,2:3], 
                    coords=c("lonutm", "latutm"), 
                    crs = CRS(proj4string(x)))

      distances <- st_distance(bird, fore[jj,], by_element = TRUE)
  
      distances2 <- cbind(as.numeric(distances), for_plt_coord4$for_plt[jj]) %>% 
          as_tibble() %>% 
          rename(dist = V1, 
                for_plt = V2) %>% 
          mutate(dist = as.numeric(dist),
                for_b = as.character(bird_sit_coord2$bir_veg[ii]),
                for_f = as.character(for_plt_coord4$for_veg[jj]),
                bird_sit = bird_sit_coord2$bird_sit[ii])
    
      if("dist1" %!in% ls()) {
          dist1 <- distances2
        } else {
          dist1 <- rbind(dist1, distances2)
        } 
    } 
  }
  
  # get only sites and plots that are 500m between each other
  if("dist1" %in% ls()) {
    dist_small <- dist1 %>% 
                    arrange(dist) %>% 
                    filter(dist <= radi_dist) %>% # diameter of the home range area of birds plus some slack if it is not circular 
                    arrange(bird_sit, dist)
    
    table(dist_small$bird_sit)

  rm(dist1)
  #! choosing how many neighbours
    close_points <- dist_small %>%
                      group_by(bird_sit) %>%
                      arrange(dist) %>% 
                      slice(1:5) %>% 
                      ungroup()

    table(close_points$bird_sit)

    if(ii == 1) {
      close_points_f <- close_points
      } else {
        close_points_f <- rbind(close_points_f, close_points)
      }
    rm(close_points)
  }
  #print(ii)
}

# connects forest and bird sites
close_points_f <- close_points_f %>% 
                    arrange(bird_sit, dist) %>% 
                    distinct()

# plot close points by park
## join coordinates
close_points_f2 <- close_points_f %>% 
  left_join(for_plt_coord2 %>% 
              rename(latutmf = latutm, lonutmf = lonutm) %>%
              select(for_plt, latutmf, lonutmf),
            by = "for_plt") %>% 
  left_join(bird_sit_coord2 %>% 
              rename(latutmb = latutm, lonutmb = lonutm) %>%
              select(bird_sit, latutmb, lonutmb),
            by = "bird_sit") 

for(ii in 1:lenght(parks)){
  (plop <- parks[ii])
  close_points_f3 <- close_points_f2 %>% 
                      filter(substr(bird_sit, 1, 4) == plop)
  bird_sit_coord2_p <- bird_sit_coord2 %>% 
                      filter(substr(bird_sit, 1, 4) == plop)
  p2 <- 
    ggplot(close_points_f3) +
      geom_segment(aes(x = lonutmb, y = latutmb, 
                        xend = lonutmf, yend = latutmf, 
                        colour = bird_sit)) +
      geom_point(data = bird_sit_coord2_p, 
                 aes(x = lonutm, y = latutm), colour = "grey") +
      geom_text(data = bird_sit_coord2_p, 
                aes(x = lonutm, y = latutm, 
                label = substr(bird_sit, 6, nchar(bird_sit))), vjust = -1.3, size = 4) +
      geom_point(aes(x = lonutmb, 
                     y = latutmb,
                     colour = bird_sit),
                size = 3) +
      geom_point(aes(x = lonutmf, 
                      y = latutmf),
                size = 3,
                color = "#186A3B",
                shape = 15) +
      theme_bw() +
      labs(title = parks[ii])
    #)
  print(p2)
  #library(plotly)
  #ggplotly(p2)
}

table(close_points_f$bird_sit) %>% dim()
table(close_points_f$bird_sit) %>% sort()

table(round(close_points_f$dist, 0)) %>% sort()

table(close_points_f$for_b) %>% sort()

table(close_points_f$for_f) %>% sort()

#? get means for all bird sites ----------------------------------------------
for_plt2 <- for_plt %>% 
                rename(for_plt = Plot_Name)

# connect the covariates of bird site and forest plots  
bird_sit_covs <- left_join(close_points_f2, for_plt2, by = "for_plt") 

dim(bird_sit_covs)
dim(bird_sit_covs %>% filter(complete.cases(.)) %>% filter(if_all(where(is.numeric), is.finite)))
bird_sit_covs[,13:ncol(bird_sit_covs)] %>% 
  summarise(across(everything(), ~sum(is.na(.)))) %>% 
  t() %>% 
  as.data.frame() %>%
  tibble::rownames_to_column("column") %>%
  arrange(-V1)

# get an average so each forest site has only one covariate value - weighted mean according to the inverse of the distance
bird_sit_covs1 <- bird_sit_covs  %>% 
                      select(-for_plt, -for_b, -for_f, 
                             -latutmf, -lonutmf, -latutmb, -lonutmb, -X, -Y, -UTMZone) %>% 
                      mutate(BA_m2ha =             ifelse(BA_m2ha == 0, BA_m2ha + 0.001, BA_m2ha),
                             BA_m2ha_Conifer =     ifelse(BA_m2ha_Conifer == 0, BA_m2ha_Conifer + 0.001, BA_m2ha_Conifer),
                             BA_m2ha_Hardwood =    ifelse(BA_m2ha_Hardwood == 0, BA_m2ha_Hardwood + 0.001, BA_m2ha_Hardwood),
                             BA_m2ha_large =       ifelse(BA_m2ha_large == 0, BA_m2ha_large + 0.001, BA_m2ha_large),
                             BA_m2ha_mature =      ifelse(BA_m2ha_mature == 0, BA_m2ha_mature + 0.001, BA_m2ha_mature),
                             BA_m2ha_pole =        ifelse(BA_m2ha_pole == 0, BA_m2ha_pole + 0.001, BA_m2ha_pole),
                             treeden_ha =          ifelse(treeden_ha == 0, treeden_ha + 0.001, treeden_ha),
                             treeden_ha_Conifer =  ifelse(treeden_ha_Conifer == 0, treeden_ha_Conifer + 0.001, treeden_ha_Conifer),
                             treeden_ha_Hardwood = ifelse(treeden_ha_Hardwood == 0, treeden_ha_Hardwood + 0.001, treeden_ha_Hardwood),
                             treeden_ha_large =    ifelse(treeden_ha_large == 0, treeden_ha_large + 0.001, treeden_ha_large),
                             treeden_ha_mature =   ifelse(treeden_ha_mature == 0, treeden_ha_mature + 0.001, treeden_ha_mature),
                             treeden_ha_pole =     ifelse(treeden_ha_pole == 0, treeden_ha_pole + 0.001, treeden_ha_pole),
                            #  seed_den_m2 =         ifelse(seed_den_m2 == 0, seed_den_m2 + 0.001, seed_den_m2),
                            #  sap_den_m2 =          ifelse(sap_den_m2 == 0, sap_den_m2 + 0.001, sap_den_m2),
                            #  regen_den_m2 =        ifelse(regen_den_m2 == 0, regen_den_m2 + 0.001, regen_den_m2),
                             shrub_avg_cov =       ifelse(shrub_avg_cov == 0, shrub_avg_cov + 0.001, shrub_avg_cov)
                             # shrub_cov_nat =       ifelse(shrub_cov_nat == 0, shrub_cov_nat + 0.001, shrub_cov_nat),
                             # shrub_cov_nonat =     ifelse(shrub_cov_nonat == 0, shrub_cov_nonat + 0.001, shrub_cov_nonat),
                             #cwd =                 ifelse(cwd == 0, cwd + 0.001, cwd)
                             ) 

# Get list of columns to calculate weighted means for
weight_cols <- c("BA_m2ha", "BA_m2ha_Conifer", "BA_m2ha_Hardwood", "BA_m2ha_large", "BA_m2ha_mature", "BA_m2ha_pole", 
                 "treeden_ha", "treeden_ha_Conifer", "treeden_ha_Hardwood", "treeden_ha_large", "treeden_ha_mature", "treeden_ha_pole", 
                 #"seed_den_m2", "sap_den_m2", "regen_den_m2", "shrub_cov_nat", "shrub_cov_nonat", 
                 "shrub_avg_cov"#, "cwd"
                 )

# Get unique bird sites
unique_sites <- unique(bird_sit_covs1$bird_sit)

# Initialize results dataframe
bird_sit_covs2 <- data.frame(bird_sit = unique_sites)

# Loop through each column to calculate weighted means
for(col in weight_cols) {
  
  # Initialize vector to store results for this column
  weighted_vals <- numeric(length(unique_sites))
  
  # Loop through each bird site
  for(i in seq_along(unique_sites)) {
    site_data <- bird_sit_covs[bird_sit_covs$bird_sit == unique_sites[i], ]
    
    # Get values and distances for this site and column
    values <- site_data[[col]]
    distances <- site_data$dist
    
    # Remove rows where the column value is NA
    non_na_idx <- !is.na(values)
    
    if(sum(non_na_idx) == 0) {
      # All values are NA, set result to NA
      weighted_vals[i] <- NA
    } else {
      # Calculate weighted mean using only non-NA values
      clean_values <- values[non_na_idx]
      clean_distances <- distances[non_na_idx]
      weights <- 1/clean_distances
      
      weighted_vals[i] <- sum(clean_values * weights) / sum(weights)
    }
  }
  
  # Add column to results with "_wei" suffix
  bird_sit_covs2[[paste0(col, "_wei")]] <- weighted_vals
}

bird_sit_covs2 <- as_tibble(bird_sit_covs2) %>% 
      mutate(BA_m2ha_perc_con = BA_m2ha_Conifer_wei/(BA_m2ha_Conifer_wei+BA_m2ha_Hardwood_wei)) %>% 
      mutate(BA_m2ha_perc_har = BA_m2ha_Hardwood_wei/(BA_m2ha_Conifer_wei+BA_m2ha_Hardwood_wei))

table(bird_sit_coord2 %>% select(bird_sit) %>% distinct() %>% mutate(park = substr(bird_sit, 1, 4)) %>% pull(park))      ## original
table(close_points_f2 %>% select(bird_sit) %>% distinct() %>% mutate(park = substr(bird_sit, 1, 4)) %>% pull(park))      ## with neighbors
table(bird_sit_covs   %>% select(bird_sit) %>% distinct() %>% mutate(park = substr(bird_sit, 1, 4)) %>% pull(park))      ## neighbors with data
table(bird_sit_covs2  %>% select(bird_sit) %>% distinct() %>% mutate(park = substr(bird_sit, 1, 4)) %>% pull(park))      ## neighbors with data

close_points_f2$for_b %>% table()

bird_sit_covs2 %>% 
  summarise(across(everything(), ~sum(is.na(.)))) %>%
  pivot_longer(everything(), names_to = "column", values_to = "na_count") %>%
  arrange(desc(na_count))

# bird_sit_covs %>% select(bird_sit, shrub_cov_nat) %>% filter(is.na(shrub_cov_nat))
# bird_sit_covs2 %>% select(bird_sit, shrub_cov_nat_wei) %>% filter(is.na(shrub_cov_nat_wei))

# NA_shr <- bird_sit_covs %>% select(bird_sit, shrub_cov_nat) %>% filter(is.na(shrub_cov_nat)) %>% pull(bird_sit)
# bird_sit_covs %>% select(bird_sit, shrub_cov_nat) %>% filter(bird_sit %in% NA_shr)
# bird_sit_covs2 %>% select(bird_sit, shrub_cov_nat_wei) %>% filter(bird_sit %in% NA_shr)

#! Output files ----------------------------------------------
print("save output files!")

if(hard_con_mix == FALSE) {
  # information of covariates for each bird site
  write_rds(bird_sit_covs2, file = glue("data/out/site_covs_fornofor_{radi_dist}m.rds"))

  # who is whose neighbor
  write_rds(close_points_f2, file = glue("data/out/neighbor_fornofor_{radi_dist}m.rds"))
}

if(hard_con_mix == TRUE) {
  # information of covariates for each bird site
  write_rds(bird_sit_covs2, file = glue("data/out/site_covs_hardcon_{radi_dist}m.rds"))

  # who is whose neighbor
  write_rds(close_points_f2, file = glue("data/out/neighbor_hardcon_{radi_dist}m.rds"))
}

cat(paste("\n\n Done \n\n\n"))

# neighbours
table(close_points_f2$for_plt)
table(close_points_f2$for_plt) %>% mean()
table(close_points_f2$for_plt) %>% sd()

# number of neightbours per park
uni_neigh <- full_join(for_plt2, close_points_f, by = "for_plt")  %>% 
                select(bird_sit, for_plt) %>% 
                filter(!is.na(bird_sit))  %>% 
                mutate(uni_nei = glue("{substr(bird_sit, 1, 4)}_{substr(for_plt, 6, 8)}")) %>% 
                mutate(park = glue("{substr(bird_sit, 1, 4)}"))

uni_neigh2 <- uni_neigh %>% 
                select(park, uni_nei) %>% 
                distinct() %>% 
                group_by(park) %>% 
                summarise(neigh = n()) %>% 
                ungroup() %>% 
                arrange(park)


